name: Update Pocket Casts History

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch Data
        env:
          POCKETCASTS_EMAIL: ${{ secrets.POCKETCASTS_EMAIL }}
          POCKETCASTS_PASSWORD: ${{ secrets.POCKETCASTS_PASSWORD }}
        run: node scripts/fetch_podcast.js

      - name: Commit and Push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/podcast_history.json
          git diff --cached --quiet || (git commit -m "chore: update podcast history" && git push)
